# Generated by Django 4.2.1 on 2023-07-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraexpense',
            name='expense_type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
